### ISSUE TITLE
About the V3 pin of CH340C

### ISSUE THREAD

**Issue by kiria-moe** [jfm92/microByte_PCB#2]
In the schematic, near the CH340C chip, there is a sentence like this:

> R9 brigde to connect to +3.3v.
Is not clear on datatsheet.

I went to search for the datasheet of CH340C, it says:

> 当使用 3.3V 工作电压时，CH340 芯片的 V3 引脚应该与 VCC 引脚相连接，同时输入外部的 3.3V 电源，并且与 CH340 芯片相连接的其它电路的工作电压不能超过 3.3V。

After translation:

> When using 3.3V working voltage, V3 pin of CH340 chip should be connected with VCC pin, and input external 3.3V power supply at the same time, and the working voltage of other circuits connected with CH340 chip should not exceed 3.3V.

It didn't said that R9 should bridge to connect to +3.3V, so I am a little bit doubtful. Will it work when V3 pin is connected to +3.3v directly?

(Sorry for my poor English and bad grammer)

**Comment by jfm92** [comment]
Hi Jiawens,
Sorry for the delayed answer, I'm a little busy nowadays.

> It didn't said that R9 should bridge to connect to +3.3V, so I am a little bit doubtful. Will it work when V3 pin is connected to +3.3v directly?

On previous versions of the board, V3 and Vcc were connected, and it worked. But the reason to add a bridge was that the chip was producing an "Electrical noise" and I was suspecting that the datasheet was badly translated, and the information was wrong. (This is the datasheet [Sparkfun translation](https://cdn.sparkfun.com/datasheets/Dev/Arduino/Other/CH340DS1.PDF) )

At this moment I don't connect V3 and VCC, and it works fine. No audible electrical noise, and no issue with RTC and CTS signals. 

Maybe this answer can help you too much, but I just can say that it works fine.

**Comment by redfox67** [comment]
If i were to add a headphone jack, would I add it before or after the amp to the speaker? does the speaker have an amp or is it in the audio chip?

**Comment by kiria-moe** [comment]
I see. I will use the same design as yours to avoid electrical noise.
Thank you for your comment. :)
